server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer3:8763/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000